version: '3'

services:
  app:
    build:
      context: ./fastapi-db-app/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=user
      - DB_PASSWORD=password
    volumes:
      - ./fastapi-db-app/:/app/
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql/
    ports:
      - "3306:3306"

volumes:
  mysql_data:
